Update OSInterface to v1.1.1 (#4)
* Update OSInterface to v1.1.1

* Update ESP_CI.yml

* Update ESP_CI.yml

diff --git a/.github/workflows/ESP_CI.yml b/.github/workflows/ESP_CI.yml
--- a/.github/workflows/ESP_CI.yml
+++ b/.github/workflows/ESP_CI.yml
@@ -15,6 +15,7 @@ on:
 
 jobs:
     Build-Test:
+        permissions: {}
         runs-on: ubuntu-latest
         env:
             GH_PAT: ${{ secrets.PMW_CI_PAT }}
@@ -52,3 +53,18 @@ jobs:
                         
                         idf.py build &&
                         pytest
+
+    success:
+        permissions: {}
+        runs-on: ubuntu-latest
+        needs:
+            - Build-Test
+        if: always()
+        steps:
+            -   name: Check merge-gatekeeper result
+                run: |
+                    if [ "${{ needs.Build-Test.result }}" = "failure" ]; then
+                      echo "Merge Gatekeeper failed."
+                      exit 1
+                    fi
+                    echo "CI passed."
