Update ESP_CI.yml

diff --git a/.github/workflows/ESP_CI.yml b/.github/workflows/ESP_CI.yml
--- a/.github/workflows/ESP_CI.yml
+++ b/.github/workflows/ESP_CI.yml
@@ -52,3 +52,18 @@ jobs:
                         
                         idf.py build &&
                         pytest
+
+    success:
+        permissions: {}
+        runs-on: ubuntu-latest
+        needs:
+            - Build-Test
+        if: always()
+        steps:
+            -   name: Check merge-gatekeeper result
+                run: |
+                    if [ "${{ needs.Build-Test.result }}" = "failure" ]; then
+                      echo "Merge Gatekeeper failed."
+                      exit 1
+                    fi
+                    echo "CI passed."
